#Длительность голосования (В секундах)
duration: 2
#Глобальный кулдаун на голосование (В секундах)
votesun-global: 15
voteday-global: 20
#Персональный кулдаун на голосование (В секундах)
votesun-personal: 10
voteday-personal: 15
#Какой нужен перевес голосов "за" для того, чтобы голосование прошло.
success-ratio: 0.6
#Какой должен быть абсолютный перевес голосов "за" чтобы голосование прошло
success-advantage: 2
#Цвета, которые использует алиса
chat-colors:
  prefix-color: "c"
  name-color: "d"
  text-color: "e"
  bracket-color: "8"
#messages:
#  join: "вассап"