#Длительность голосования
duration: 900
#Глобальный кулдаун на голосование
votesun-global: 12000
voteday-global: 48000
#Персональный кулдаун на голосование
votesun-personal: 18000
voteday-personal: 72000
#Какой нужен перевес голосов "за" для того, чтобы голосование прошло.
success-ratio: 0.6
#Какой должен быть абсолютный перевес голосов "за" чтобы голосование прошло
success-advantage: 2
#messages:
#  join: "вассап"