name: Alisa # Имя плагина
main: org.shy.alisa.Main # Путь к главному классу (тому, который наследует JavaPlugin)
author: Flareon # Автор плагина
version: 0.1 # Версия плагина
api-version: '1.16'
description: The best in the world plugin # Описание плагина
commands:
  colors:
    description: Colors list
    usage: "/colors"
  votesun:
    description: Voting for a change of weather
    usage: "/votesun"
  voteday:
    description: Voting for a change of daytime
    usage: "/voteday"
  'yes':
    description: Vote yes
    usage: "/yes"
  'no':
    description: Vote no
    usage: "/no"
#  'ahelp':
#    description: All commands for Alisa
#    usage: "/ahelp"