name: Alisa
main: org.shy.alisa.FLAlisa
author: Flareon
version: 0.2
api-version: '1.16'
description: The best in the world plugin


commands:
  ahelp:
    description: Список доступных комманд
    usage: "/ahelp"
    default: true
#  colors:
#    description: Список доступных цветов в чате
#    usage: "/colors"
#    default: true
  aseen:
    description: Узнать когда игрок был последний раз на сервере
    usage: "/aseen"
    default: true
  server:
    description: Время до рестарта сервера
    usage: "/server"
    default: true
    aliases: [aserver]
  'yes':
    description: Проголосовать "Да"
    usage: "/yes"
    default: true
  'no':
    description: Проголосовать "Нет"
    usage: "/no"
    default: true
  votesun:
    description: Голосование за отключение дождя
    usage: "/votesun"
    default: true
  voteday:
    description: Голосование за смену дня
    usage: "/voteday"
    default: true
  inf:
    description: Информация по пунктам правил
    usage: "/inf <point rule>"
    default: true
  alisa:
    description: Все комманды администратора
    usage: "/alisa <command>"
    default: op
  alisa read:
      description: Посмотреть значение в конфиге
      usage: "/alisa read <Ключ>"
      default: op
  alisa set:
      description: Изменить значение в конфиге
      usage: "/alisa set <ключ> <значение>"
      default: op
  alisa reloadconfig:
      description: Перезагрузка конфига
      usage: "/alisa reloadconfig"
      default: op
  alisa getname:
      description: Получить Ник игрока по UUID
      usage: "/alisa reloadconfig"
      default: op
  alisa getuuid:
      description: Получить UUID игрока по Нику
      usage: "/alisa reloadconfig"
      default: op